# Generated by Django 5.2.4 on 2025-09-07 18:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oa_events', '0001_initial'),
        ('problems', '0003_problem_memory_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='company_tag',
            field=models.ForeignKey(blank=True, help_text="Optional: Tag this problem with a company if it's an OA/Interview problem.", null=True, on_delete=django.db.models.deletion.SET_NULL, to='oa_events.company'),
        ),
    ]
