services:
  web:
    build: .
    command: gunicorn backend.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app  # This links your local code for live updates
    expose:
      - 8000
    
  nginx:
    image: nginx:latest
    ports:
      - "80:80" # You can access the site at http://localhost
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - web