# Generated by Django 5.2.4 on 2025-07-27 14:02

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0003_solution'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codesubmission',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
