# Generated by Django 5.2.4 on 2025-07-27 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0004_alter_codesubmission_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='codesubmission',
            name='verdict',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.DeleteModel(
            name='Solution',
        ),
    ]
