# Generated by Django 5.2.4 on 2025-09-07 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the company (e.g., Google, Amazon)', max_length=100, unique=True)),
                ('logo', models.ImageField(blank=True, help_text='Upload company logo (optional)', null=True, upload_to='company_logos/')),
            ],
            options={
                'verbose_name_plural': 'Companies',
                'ordering': ['name'],
            },
        ),
    ]
