# Generated by Django 5.2.4 on 2025-09-07 18:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oa_events', '0001_initial'),
        ('problems', '0004_problem_company_tag'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OAEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='e.g., Google OA Round, Amazon SDE Interview', max_length=200)),
                ('event_date', models.DateField(help_text='When did this OA/Interview take place?')),
                ('description', models.TextField(blank=True, help_text='General notes or observations about the event (optional).')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ai_summary', models.TextField(blank=True, help_text='AI-generated summary of key concepts from discussions.', null=True)),
                ('company', models.ForeignKey(help_text='Which company conducted this event?', on_delete=django.db.models.deletion.CASCADE, to='oa_events.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('problems', models.ManyToManyField(help_text='Select problems featured in this event.', related_name='oa_events', to='problems.problem')),
            ],
            options={
                'verbose_name': 'OA/Interview Event',
                'verbose_name_plural': 'OA/Interview Events',
                'ordering': ['-event_date', 'company__name', 'title'],
                'unique_together': {('company', 'event_date', 'title')},
            },
        ),
    ]
