# Generated by Django 5.2.4 on 2025-09-07 20:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oa_events', '0002_oaevent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OAEventDiscussionComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(help_text='The content of the discussion comment.')),
                ('timestamp', models.DateTimeField(auto_now_add=True, help_text='When the comment was posted.')),
                ('is_spam', models.BooleanField(default=False, help_text='Flag for potential spam (for moderation).')),
                ('event', models.ForeignKey(help_text='The OA Event this comment belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='discussion_comments', to='oa_events.oaevent')),
                ('user', models.ForeignKey(help_text='The user who posted this comment.', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'OA Event Discussion Comment',
                'verbose_name_plural': 'OA Event Discussion Comments',
                'ordering': ['timestamp'],
            },
        ),
    ]
